# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='edad',
        ),
        migrations.AddField(
            model_name='documentos',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
